---
apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  name: bronco
  labels:
    cloud: BareMetal
    vendor: OpenShift
    common-du-416: "true"
    group-dellr760-vse4: ""
spec:
  hubAcceptsClient: true
---
apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: bronco
  namespace: bronco
spec:
  clusterName: bronco
  clusterNamespace: bronco
  clusterLabels:
    cloud: BareMetal
    vendor: OpenShift
  applicationManager:
    enabled: true
  certPolicyController:
    enabled: true
  iamPolicyController:
    enabled: true
  policyController:
    enabled: true
  searchCollector:
    enabled: true
